---
- name: Playbook
  vars_files:
    - ./vars_file.yaml
  hosts: all
  become: true
  tasks:
    - name: 'Ensure apache giid is set to custom value'
      group:
        name: 'apache'
        state: present
        gid: 69
    - name: 'Ensure apache uid is set to custom value'
      user:
        name: 'apache'
        state: present
        group: 'apache'
        uid: 69
    - name: 'upgrade'
      dnf:
        name: '*'
        state: latest
      tags:
        - 'system upgrade'

    - name: 'Install Git'
      dnf:
        name: git
        state: present
      tags:
        - 'utilities'

    - name: 'Install vim'
      dnf:
        name: 'vim'
        state: present
      tags:
        - 'utilities'

    - name: 'Install Apache'
      dnf:
        name: 'httpd'
        state: present
      tags:
        - 'apache'

    - name: 'Install Apache Extra Mods'
      dnf:
        name: 'mod_{{ item }}'
        state: present
      loop: '{{ apache.extra_mods }}'
      tags:
        - 'apache'

    - name: 'Enable Apache'
      systemd:
        name: 'httpd'
        state: started
        enabled: true
      tags:
        - 'apache'

    - name: 'Get extra repos'
      dnf:
        name: '{{ item }}'
        disable_gpg_check: true
        state: present
      loop: '{{ repos }}'
      tags:
        - 'repos'

    - name: 'Install PHP 8.1 using remi repo'
      dnf:
        name: '@php:remi-8.1'
        state: present
      tags:
        - 'php'

    - name: 'Install PHP extensions'
      dnf:
        name: '{{ item }}'
        state: present
      loop: '{{ php.extensions }}'
      tags:
        - 'php'

    - name: 'Install PHP FPM'
      dnf:
        name: 'php-fpm'
        state: present
      tags:
        - 'php'
        - 'php_fpm'

    - name: 'Enable PHP-fpm'
      systemd:
        name: 'php-fpm'
        state: started
        enabled: true
      tags:
        - 'php'

    - name: 'Stop firewall'
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      tags:
        - 'firewalld'

    - name: 'Configure Selinux'
      selinux:
        policy: 'targeted'
        state: 'permissive'
      tags:
        - 'selinux'
